# For detailed information about docker-compose visit https://docs.docker.com/compose/
# To start all docker containers required to execute the tests locally run:
# docker-compose up

version: '2'
services:
  cassandra:
    image: cassandra:3
    ports:
      - "9042:9042"
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  sqs:
    image: s12v/elasticmq:0.12.0
    ports:
      - "9324:9324"
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/src/test/travis:/mqtt/config/conf.d
